#define CORRECT_EXIT_STATUS             0
#define INCORRECT_ARGS_NUMBER_STATUS    1
#define FILE_DOESNT_EXISTS_STATUS       2
#define KNOWN_EXCEPTION_CAUGHT_STATUS   3
#define UNKNOWN_EXCEPTION_CAUGHT_STATUS 4